accounts:
  ecadlabs:
    key: edpkvP1NXoo8vhYbPSvXdy466EHoYWBpf6zmjghB2p3DwJPjbB5nsf
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "5000000000000"
  smartpy:
    key: edpktv8Advoagbpo5TiyyDnmC1Mqne6vJMaXQ2vvuzUfJnBfMKJmdC
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "5000000000000"
  bruno:
    key: edpkuu3jmS3kbaLYTmyVaPHaxowC1KP8fDSrLoJhcvip1Cm2tK5QCd
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "5000000000000"
  tezosil:
    key: edpkvQj8r3YigN6QFsDRaKQCoxDNhKK4whDUkFkw6Gom36d86uhEbv
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "5000000000000"
  pirbo:
    key: edpkuGH2TWTQ5JrwzBLGRu5is1h7vcv5e5LN45VfqmXS5zaTUMpopH
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "5000000000000"
  luke:
    key: p2pk66gP3wq6k9QgNwAgaGLeXc3YFfrxgYdC7cdYuJWAHYBw4hExVHW
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "5000000000000"
  marco:
    key: edpkvMWHXeETjH4i2h2ngkG2y6aVdgtW99pQ3SuHJoWNEPKANzVRLT
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "5000000000000"
  tz1THUNA:
    # Romain's faucet
    key: edpkuh3WSwziyd6nXqDXeh48vZHp5ETxFd43EdkbzhmW98BvuLXK81
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "500000000000000"
  tzbtc_admin:
    # admin for the test token contract that stands in for tzBTC.
    # (put here to test liquidity baking)
    key: edpkuBknW28nW72KG6RoHtYW7p12T6GKc7nAbwYX5m8Wd9sDVC9yav
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "5000000000000000"
  oxheadbaker:
    bootstrap_balance: "5000000000000"
    is_bootstrap_baker_account: true
    type: secret
    # key injected by pulumi
  tqfree:
    bootstrap_balance: "5000000000000000"
    is_bootstrap_baker_account: false
    type: secret
    # key injected by pulumi

node_config_network:
  activation_account_name: oxheadbaker
  chain_name: TEZOS_GRANADANET_2021-05-21T15:00:00Z
  genesis:
    block: BLockGenesisGenesisGenesisGenesisGenesisd4299hBGVoU
    protocol: PtYuensgYBb3G3x1hLLbCmcav8ue8Kyd2khADcL5LsT5R1hcXex
    timestamp: "2021-05-21T15:00:00Z"
  user_activated_upgrades:
    - level: 4095
      replacement_protocol: PtGRANADsDU8R9daYKAgWnQYAJ64omN1o3KMGVCykShA97vQbvV

bootstrap_peers:
  - granadanet.smartpy.io
  - granadanet.tezos.co.il
  - granadanet.kaml.fr

images:
  octez: tezos/tezos:v10.3

nodes:
  tezos-baking-node:
    instances:
      - bake_using_accounts:
          - oxheadbaker
        config:
          shell:
            history_mode: archive
          rpc:
            cors-headers: [ "content-type" ]
            cors-origin: [ "*" ]
        is_bootstrap_node: true
    runs:
      - baker
      - endorser
      - octez_node
    storage_size: 30Gi
  # Overwrite default values.yaml tezos-node
  tezos-node: null

## Chain has already been activated. `activation` is commented out to indicate
## internally that it shouldn't try and activate the chain again.
##
# activation:
#   protocol_hash: PsFLorenaUUuikDWvMDr6fGBRG8kt3e3D3fHoXK1j1BFRxeSH4i
#   protocol_parameters:
#     preserved_cycles: 3
#     blocks_per_cycle: 2048
#     blocks_per_commitment: 16
#     blocks_per_roll_snapshot: 128
#     blocks_per_voting_period: 10240
#     time_between_blocks:
#       - "30"
#       - "20"
#     endorsers_per_block: 32
#     hard_gas_limit_per_operation: "1040000"
#     hard_gas_limit_per_block: "10400000"
#     proof_of_work_threshold: "70368744177663"
#     tokens_per_roll: "8000000000"
#     michelson_maximum_type_size: 1000
#     seed_nonce_revelation_tip: "125000"
#     origination_size: 257
#     block_security_deposit: "512000000"
#     endorsement_security_deposit: "64000000"
#     baking_reward_per_endorsement:
#       - "1250000"
#       - "187500"
#     endorsement_reward:
#       - "1250000"
#       - "833333"
#     cost_per_byte: "250"
#     hard_storage_limit_per_operation: "60000"
#     quorum_min: 2000
#     quorum_max: 7000
#     min_proposal_quorum: 500
#     initial_endorsers: 24
#     delay_per_missing_endorsement: "4"
#     test_chain_duration: "1966080"

protocols:
  - command: 010-PtGRANAD

full_snapshot_url: null
rolling_snapshot_url: null
