accounts:
  oxheadbaker:
    # tz1foXHgRzdYdaLgX6XhpZGxbBv42LZ6ubvE
    bootstrap_balance: "9700000000000"
    is_bootstrap_baker_account: true
    # key injected by pulumi
  oxheadfree:
    # an account with a lot of money in it
    # tz1foxFdz2ieSj8P9YxKYBTEqYbgFXXEeiQY
    key: edpkubSgCoMjB2a6vPWRNRHfGa6HUFfFyEUKoEQhWC8osnav8QzBdJ
    bootstrap_balance: "50000000000000000"
    is_bootstrap_baker_account: false
  bakingbadfaucet:
    # baking bad maintains a telegram faucet bot
    # tz1KhnTgwoRRALBX6vRHRnydDGSBFsWtcJxc
    key: edpkuFRauFAdhipQu9s4xmfNJWmtLxPKpoaoG41gYGq5AgUA43Vxqx
    is_bootstrap_baker_account: false
    bootstrap_balance: "5000000000000000"
  tz1THUNA:
    # tz1THUNARo58aD5YdNGYPnWNnvd8yHPrMdsF
    # Romain's faucet
    key: edpkuh3WSwziyd6nXqDXeh48vZHp5ETxFd43EdkbzhmW98BvuLXK81
    is_bootstrap_baker_account: false
    bootstrap_balance: "50000000000000000"
  foundationfaucet:
    # TF funds to deploy more bakers later if needed
    # chris.pinnock@tezos.foundation
    # tz1LwEoAHSxsMm8dECaQTGNsGvXCD9HeBgdj
    key: edpku2v3DA5WFGE7LSjNVC8FTVhy2LdSu8U34GYaT1zfzZaugCbpVU
    is_bootstrap_baker_account: false
    bootstrap_balance: "50000000000000000"
  oxheadfaucet:
    # the faucet on teztnets platform
    # tz1a4GT7THHaGDiTxgXoatDWcZfJ5j29z5RC
    key: edpkvGYHoY5kwq13Ak6r4fLa1GGSHKJZVe7xJFV6ZgHwdZeaHy3WZj
    is_bootstrap_baker_account: false
    bootstrap_balance: "15000000000000"
  tf:
    # tz3Q67aMz7gSMiQRcW729sXSfuMtkyAHYfqc
    key: p2pk66gP3wq6k9QgNwAgaGLeXc3YFfrxgYdC7cdYuJWAHYBw4hExVHW
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  marco:
    # Marco Schurtenberger
    key: edpkubw32gvTfUYRERGECHbMTsiLdM9z9JrEXGVEahbZf9yMhTozSg
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  andrewk:
    # tz1aWXP237BLwNHJcCD4b3DutCevhqq2T1Z9
    key: edpkvNGUd3xcBNmPWRbXJoS6WEvxu1BVoWjHr7ab7QoAJFFqhx9tkR
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  pirbo:
    # tz1PirbogVqfmBT9XCuYJ1KnDx4bnMSYfGru
    key: edpkvaQpRgsSGPJSY91sjNArLMgpTUHmmfkvuSekwos43uze2H2EFM
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  ecadlabs:
    # tz1cjyja1TU6fiyiFav3mFAdnDsCReJ12hPD
    key: edpkvP1NXoo8vhYbPSvXdy466EHoYWBpf6zmjghB2p3DwJPjbB5nsf
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  ecadlabs_2:
    # tz1RuHDSj9P7mNNhfKxsyLGRDahTX5QD1DdP
    key: edpkthQu5xeKjD9Dxh5tAf3f61z2Nteqk9xRVPVoZekk1CF738zbcJ
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  fredcy:
    # tz1KkJtLB9pMdLKNpVRNZw9zmysrxKmYcRGU
    key: edpkvTUqzRYhotk2YFnemLfBk8apvcSVNwTSxB6F6CaXUA64CRXgHN
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  pasqualepinto:
    # tz1hoyMUiJYYr4FRPMU8Z7WJzYkqgjygjaTy
    key: edpkugfNCoDerYV9pq1EfGgjX9mPk3uxX2wXhRz85dUNMtTUPnhjJE
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  rich_ayotte:
    # Richard Ayotte (https://twitter.com/RichAyotte or anarcode)
    # tz1Sp6HTbbsHDhGDjqsucvRzV9rVe8LTb7c4
    key: edpktoAgXAvtBFojuKPoigboyPA6mPJ3pyR1JP8XES6Lg1rkf1a3T5
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  vincent_xtzmaster:
    # tz1M9b1sKoh5GB7AiBiqdMrjMMyvuhsZua5n
    key: edpktrpiJF24hcmJ22tfDaFWuFihZYbSgr15vFAGUmHThtnr37BZqX
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  killian_d:
    # tz1gBnaS1n7LKqpaRnyBX5MSmamadXXfzNpt
    key: edpkv7AqKLxQXWa2tHcPbMnah1JbMUHohvmvgPS7nVaB7kdNnrg1XW
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  feeny:
    key: edpktmqPi9eRefM9ZrwsPNAdg9832UDg3r894J4rkBGfUhpqZpqx6y
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  albin:
    # tz1YtB3Hn6oghVk96vkpZt6PHrfbyRY1ciL3
    key: edpkuc4NCkkmTyLogcU32b7sU363J2jggs19EyBzhmms6JmjQZxEJo
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  blueledger:
    # Mike Kerhnaghan
    # tz1bQYMFieZHomNPjJvpp2g7PuhxRPDxpnFt
    key: edpkvMWcnT7ha4m9kDv82X11Yx39xyowquUdBKpne5tpUyajcbjH6L
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
    
node_config_network:
  activation_account_name: oxheadbaker
  chain_name: TEZOS_NAIROBINET_2023-04-20T15:00:00Z
  genesis:
    protocol: Ps9mPmXaRzmzk35gbAYNCAw6UXdE2qoABTHbN2oEEc1qM7CwT9P
    timestamp: "2023-04-20T15:00:00Z"

nodes:
  tezos-baking-node:
    instances:
      - bake_using_accounts:
          - oxheadbaker
        config:
          shell:
            history_mode: rolling
          rpc:
            cors-headers: [ "content-type" ]
            cors-origin: [ "*" ]
        is_bootstrap_node: true
    runs:
      - octez_node
      - baker
      - accuser
        #- vdf
    readiness_probe: false
    storage_size: 20Gi
  # Overwrite default values.yaml rolling-node
  rolling-node: null

full_snapshot_url: null
rolling_snapshot_url: null
rolling_tarball_url: null
archive_tarball_url: null

snapshot_source: https://snapshots.tezos.marigold.dev/api/tezos-snapshots.json
snapshot_metadata_network_name: nairobinet

images:
  octez: tezos/tezos:v18.1

protocols:
  - command: PtNairob
    vote:
      liquidity_baking_toggle_vote: "pass"

bootstrap_peers:
  - nairobinet.tzboot.net
  - nairobinet.tzinit.org
#   - mumbainet.visualtez.com
