accounts:
  ecadlabs:
    # tz1cjyja1TU6fiyiFav3mFAdnDsCReJ12hPD
    key: edpkvP1NXoo8vhYbPSvXdy466EHoYWBpf6zmjghB2p3DwJPjbB5nsf
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  smartpy:
    # tz1SMARcpWCydHsGgz4MRoK9NkbpBmmUAfNe
    key: edpkuyuJirNU14hEma1u7f3Qhx7uHZxzuXDyvmjRwaAsFFFqYGkzHx
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  tezosil:
    # tz1VWasoyFGAWZt5K2qZRzP3cWzv3z7MMhP8
    key: edpkvQj8r3YigN6QFsDRaKQCoxDNhKK4whDUkFkw6Gom36d86uhEbv
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  pirbo:
    # tz1PirbogVqfmBT9XCuYJ1KnDx4bnMSYfGru
    key: edpkvaQpRgsSGPJSY91sjNArLMgpTUHmmfkvuSekwos43uze2H2EFM
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  andrewk:
    key: edpkvNGUd3xcBNmPWRbXJoS6WEvxu1BVoWjHr7ab7QoAJFFqhx9tkR
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  blockwatch:
    # tz1cXeGHP8Urj2pQRwpAkCdPGbCdqFUPsQwU
    key: edpktqRmZsGN2WEyghfqrZvn8c7xmA1xs3vDta71CsCjtHiSRMkG1z
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  marco:
    key: edpkubw32gvTfUYRERGECHbMTsiLdM9z9JrEXGVEahbZf9yMhTozSg
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  fifthelement:
    key: edpkujqmLUVGNbSNZV7CBMdtXAMGTTwJDQoXp2aRGrotys51rYvaRi
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  utdrmac:
    # tz1X9arq5VDQdeUmgsrz7C8CxWVzVAJFbGaB
    key: edpkvWPKvk8A8tk97Sr8CbyKJLekuHYwQ5R2rJ3Qe23jvtewaRAdYp
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  primate:
    # tz1S9Z6VAERuwQ1QQ6FqnREiT99ZB9wdGE9z
    key: edpkvM7PAJiTMTAeRB1W77U5jF17aCV1vkBoKPScs8vmAd56t2BE72
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  N1029676:
    # tz1N1W47vNFSBPqnWbUoAw65LFHzv2PGqS4x
    key: edpkuZ6pf5esZLnVJ7XGZbfQ6s9yFsrGW49nhrRVrCZ6ghqRvGR1n5
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  vincent_xtzmaster:
    # tz1Kr7EBSj86kbQFgCSLKo8JtvFQvYEU4SuH
    key: edpkuVw1DAAJ1bucCkNJ48e9L8Md8meXogKnMUp1Z6sey1NFhCxmvU
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  neoktalabs_julien:
    # tz1gECNgGXb4vzsEhAvX6a72AsAGJiQS8DLf
    key: edpkv99446esWVTgGSNsfeZCpeLYbq1e69tae3Fpw22GXcMHQeRSVg
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  coredump:
    # tz1Wn7JnLVf7PpTbaLQNzmNaF9z9UudWHGBR
    key: edpkttKzcNNCjanS2De2Nagnpg9Bk1SoNhxDC1hqCFvHHFjfeeBK1m
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  german:
    # german wants to be a baker, but not bootstrap
    # tz1TGKSrZrBpND3PELJ43nVdyadoeiM1WMzb
    key: edpktjm6QS9TwK6z9VX36Gucknwag94EzfCiu741i8q373W4V4y24R
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "2000000000000"
  ping:
    # tz1MvCE9dczhoij2bd4sLL2AfVuMtWfFAoCN
    key: edpkvZcJNTNG3q4A4N42eNPPCtUDT5jffMCYwiD7QLzRGZ4CQR8pyj
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  saroupille:
    # françois wants to be a baker, but not bootstrap
    # tz1QXAAasy8TciwfvDC4a7MWo1tm3K37uN9Y
    key: edpkvMBeXH4h8H97b8qfPkv2mA9TE6McfsffLGgG2Jg5nhUESaVt5J
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "2000000000000"
  saroupille2:
    # françois wants to be a baker, but not bootstrap
    # tz1ZaHCkooCR63bSsQhLf8WLKj9sQG5RTthP
    key: edpkueS4HbicvgHo1Y9uPp6ZaZ8kgMJBJg2uB4Zm539Wf7qvJA5g1U
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "2000000000000"
  victor:
    # tz1VicarbXb4uAY12pQBAREHUimYCxjfKbLa
    key: edpkujMeTHyUEK4gqCBXHDL9yXYiHnJJ4C58AHnmgAKyfFZXcBRngB
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  tz1THUNA:
    # tz1THUNARo58aD5YdNGYPnWNnvd8yHPrMdsF 
    # Romain's faucet
    key: edpkuh3WSwziyd6nXqDXeh48vZHp5ETxFd43EdkbzhmW98BvuLXK81
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "500000000000000"
  julien:
    # for stress testing
    # tz1PicoD6HTZFNkRpN84VFUvdpT7D6xoR2QD
    key: edpktnArvYkSArFUGiBN4cmDmor9qwyTFCbAKEMbeSdT3z563SdTXm
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "500000000000000"
  bakingbadfaucet:
    # baking bad maintains a telegram faucet bot
    # tz1KhnTgwoRRALBX6vRHRnydDGSBFsWtcJxc
    key: edpkuFRauFAdhipQu9s4xmfNJWmtLxPKpoaoG41gYGq5AgUA43Vxqx
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "500000000000000"
  oxheadbaker:
    # Oxhead Alpha's baker hosted in teztnets.xyz infra
    # tz1foXHgRzdYdaLgX6XhpZGxbBv42LZ6ubvE
    bootstrap_balance: "1000000000000"
    is_bootstrap_baker_account: true
    type: secret
    # key injected by pulumi
  oxheadfree:
    # an account with a lot of money in it
    # tz1foxFdz2ieSj8P9YxKYBTEqYbgFXXEeiQY
    key: edpkubSgCoMjB2a6vPWRNRHfGa6HUFfFyEUKoEQhWC8osnav8QzBdJ
    bootstrap_balance: "5000000000000000"
    is_bootstrap_baker_account: false
    type: public

node_config_network:
  activation_account_name: oxheadbaker
  chain_name: TEZOS_HANGZHOUNET_2021-11-04T15:00:00Z
  genesis:
    block: BLockGenesisGenesisGenesisGenesisGenesis7e8c4d4snJW
    protocol: Ps9mPmXaRzmzk35gbAYNCAw6UXdE2qoABTHbN2oEEc1qM7CwT9P
    timestamp: "2021-11-04T15:00:00Z"
  user_activated_upgrades:
    - level: 8191
      replacement_protocol: PtHangz2aRngywmSRGGvrcTyMbbdpWdpFKuS4uMWxg2RaH9i1qx

bootstrap_peers:
  - hangzhounet.smartpy.io
  - hangzhounet.kaml.fr
  - hangzhounet.boot.tez.ie

images:
  octez: tezos/tezos:v12.0

nodes:
  tezos-baking-node:
    instances:
      - bake_using_accounts:
          - oxheadbaker
        config:
          shell:
            history_mode: archive
          rpc:
            cors-headers: [ "content-type" ]
            cors-origin: [ "*" ]
        is_bootstrap_node: true
    runs:
      - baker
      - endorser
      - octez_node
      - accuser
    storage_size: 80Gi
  # Overwrite default values.yaml rolling-node
  rolling-node: null

activation:
  protocol_hash: PtGRANADsDU8R9daYKAgWnQYAJ64omN1o3KMGVCykShA97vQbvV
  protocol_parameters:
     preserved_cycles: 3
     blocks_per_cycle: 4096
     blocks_per_commitment: 32
     blocks_per_roll_snapshot: 256
     blocks_per_voting_period: 20480
     time_between_blocks:
       - "20"
       - "10"
     endorsers_per_block: 256
     hard_gas_limit_per_operation: "1040000"
     hard_gas_limit_per_block: "5200000"
     proof_of_work_threshold: "70368744177663"
     tokens_per_roll: "8000000000"
     seed_nonce_revelation_tip: "125000"
     origination_size: 257
     block_security_deposit: "640000000"
     endorsement_security_deposit: "2500000"
     baking_reward_per_endorsement:
       - "78125"
       - "11719"
     endorsement_reward:
       - "78125"
       - "52083"
     cost_per_byte: "250"
     hard_storage_limit_per_operation: "60000"
     quorum_min: 2000
     quorum_max: 7000
     min_proposal_quorum: 500
     initial_endorsers: 192
     delay_per_missing_endorsement: "2"
     liquidity_baking_escape_ema_threshold: 100000
     liquidity_baking_subsidy: '2500000'
     liquidity_baking_sunset_level: 525600
     minimal_block_delay: '15'
     michelson_maximum_type_size: 1000

protocols:
  - command: 011-PtHangz2

full_snapshot_url: null
rolling_snapshot_url: null
rolling_tarball_url: null
archive_tarball_url: null
