node_config_network:
  activation_account_name: oxheadbaker
  chain_name: TEZOS_IDIAZABALNET_2021-12-07T15:00:00Z
  genesis:
    block: BLockGenesisGenesisGenesisGenesisGenesis761b2dAGmbT
    protocol: Ps9mPmXaRzmzk35gbAYNCAw6UXdE2qoABTHbN2oEEc1qM7CwT9P
    timestamp: "2021-12-07T15:00:00Z"

protocols:
  - command: alpha

activation:
  protocol_hash: ProtoALphaALphaALphaALphaALphaALphaALphaALphaDdp3zK
  protocol_parameters:
    preserved_cycles: 3
    blocks_per_cycle: 2048
    blocks_per_commitment: 64
    blocks_per_stake_snapshot: 512
    blocks_per_voting_period: 40960
    hard_gas_limit_per_operation: '1040000'
    hard_gas_limit_per_block: '5200000'
    proof_of_work_threshold: '-1'
    tokens_per_roll: '8000000000'
    seed_nonce_revelation_tip: '125000'
    baking_reward_fixed_portion: '10000000'
    baking_reward_bonus_per_slot: '4286'
    endorsing_reward_per_slot: '2857'
    hard_storage_limit_per_operation: '60000'
    origination_size: 257
    cost_per_byte: '250'
    quorum_max: 7000
    quorum_min: 2000
    min_proposal_quorum: 500
    liquidity_baking_subsidy: '2500000'
    liquidity_baking_sunset_level: 525600
    liquidity_baking_escape_ema_threshold: 100000
    max_operations_time_to_live: 120
    round_durations:
      round0: "30"
      round1: "45"
    consensus_committee_size: 7000
    consensus_threshold: 4667
    minimal_participation_ratio:
      numerator: 2
      denominator: 3
    max_slashing_period: 2
    frozen_deposits_percentage: 10
    double_baking_punishment: "640000000"
    ratio_of_frozen_deposits_slashed_per_double_endorsement:
      numerator: 1
      denominator: 2
    delegate_selection: "random"

nodes:
  tezos-baking-node:
    instances:
      - bake_using_accounts:
          - oxheadbaker
        config:
          shell:
            history_mode: archive
          rpc:
            cors-headers: [ "content-type" ]
            cors-origin: [ "*" ]
        is_bootstrap_node: true
    runs:
      - octez_node
      - baker
    storage_size: 80Gi
  # Overwrite default values.yaml tezos-node
  tezos-node: null

bootstrap_peers: []

full_snapshot_url: null
rolling_snapshot_url: null
rolling_tarball_url: null
archive_tarball_url: null

images:
  # the container tag is moving as more code is merged to the branch
  # here, put the actual container digest to make sure we pick the right one
  octez: registry.gitlab.com/nomadic-labs/tezos@sha256:e242f52636fcc4e6704c46e2ea6d3463ad1b5574ad2ccaf15053d6a73060be0c

# We give:
# * 2 million for each of nomadic's 20 "training wheels" bakers
# * 667k per community baker
# 26 community bakers * 667k = 17,342,000
# 20 NL bakers * 2,000,000 = 40,000,000
# Total stake (excluding Romain's faucet and oxheadfree which is just a bank) = 57,342,000)
# NL wants ~67% stake of the network: 57,342,000/3*2 = 38,228,000
# NL's stake: 2,000,000 * 20 = 40,000,000
accounts:
  oxheadbaker:
    # tz1foXHgRzdYdaLgX6XhpZGxbBv42LZ6ubvE
    bootstrap_balance: '667000000000'
    is_bootstrap_baker_account: true
    type: secret
    # key injected by pulumi
  pirbo:
    # tz1PirbogVqfmBT9XCuYJ1KnDx4bnMSYfGru
    key: edpkvaQpRgsSGPJSY91sjNArLMgpTUHmmfkvuSekwos43uze2H2EFM
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  andrewk:
    key: edpkvNGUd3xcBNmPWRbXJoS6WEvxu1BVoWjHr7ab7QoAJFFqhx9tkR
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  saroupille:
    # tz1QXAAasy8TciwfvDC4a7MWo1tm3K37uN9Y
    key: edpkvMBeXH4h8H97b8qfPkv2mA9TE6McfsffLGgG2Jg5nhUESaVt5J
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  hai:
    # tz1ZaHCkooCR63bSsQhLf8WLKj9sQG5RTthP
    key: edpkueS4HbicvgHo1Y9uPp6ZaZ8kgMJBJg2uB4Zm539Wf7qvJA5g1U
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  mariano_ceibo:
    # tz1T7bTfbw1PsDAKFfBN24ediaqgw8FTu3qd
    key: edpkv9xYGRddWjy9XMVeUq5d7gxWm3eVgYarrpmNW1qVvvRpmJq76G
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  fifthelement:
    key: edpkujqmLUVGNbSNZV7CBMdtXAMGTTwJDQoXp2aRGrotys51rYvaRi
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  coredump:
    # tz1Wn7JnLVf7PpTbaLQNzmNaF9z9UudWHGBR
    key: edpkttKzcNNCjanS2De2Nagnpg9Bk1SoNhxDC1hqCFvHHFjfeeBK1m
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  marco:
    key: edpkubw32gvTfUYRERGECHbMTsiLdM9z9JrEXGVEahbZf9yMhTozSg
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  baketzforme:
    # tz1edUYGqBtteStneTGDBrQWTFmq9cnEELiW
    key: edpkuEoVW7HM9ehiec9exPfHrsFkT1f3jV8JxFWQHP23VX6K5EnVtD
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  vincent_xtzmaster:
    # tz1XMiZwHpHZ8a1AfwRWKfzLskJgZNyV8PHs
    key: edpkvaZQ6tt9XgJJTonjFpzwaqDV7RWUQMT7TmntBJ5yXmDsPb8T7L
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  daniel_jean:
    # tz1RBECWBXv4tKcuDbxYmBguvdn8wzjrejHg
    key: edpkucJ7Nccy2wyaU4B2Ch4rxS4reiTfc7349pKtemcd4yLeXmbAwb
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  olivier_blockwatch:
    # tz1cXeGHP8Urj2pQRwpAkCdPGbCdqFUPsQwU
    key: edpktqRmZsGN2WEyghfqrZvn8c7xmA1xs3vDta71CsCjtHiSRMkG1z
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  ecadlabs:
    # tz1cjyja1TU6fiyiFav3mFAdnDsCReJ12hPD
    key: edpkvP1NXoo8vhYbPSvXdy466EHoYWBpf6zmjghB2p3DwJPjbB5nsf
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  smartpy:
    # tz1SMARcpWCydHsGgz4MRoK9NkbpBmmUAfNe
    key: edpkuyuJirNU14hEma1u7f3Qhx7uHZxzuXDyvmjRwaAsFFFqYGkzHx
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  neoktalabs_julien:
    # tz1RJ74UepJA9tigjoEeUEFajowzVB3QQaVx
    key: edpktnHv9X4PjoSHqzMGZf7oF6arxZbedxKTmEgcL6xS3XZ3TA1MUE
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  michael_kernaghan:
    # tz1e42w8ZaGAbM3gucbBy8iRypdbnqUj7oWY
    key: edpkuRkcStobJ569XFxmE6edyRQQzMmtf4ZnmPkTPfSQnt6P3Nym2V
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  mack_baise:
    # tz1SHw5vBDYNgGdUPJi57kVrEb2kFue4Yxa4
    key: edpkvKJ9voHuSBi8TApVowCu7D8hQneXGWdEHuSEMDjQDyxD9h6PYk
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  richard_ayotte:
    # tz1ituzNz9MGaMSL9dVDN7jE5SArCEWNmZbS
    key: edpkuty8oXRwNH5zRLfGkTyL2ukMVhGiht3qG8VNU5beD4NgP8X3gw
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  fredcy:
    # tz1KkJtLB9pMdLKNpVRNZw9zmysrxKmYcRGU
    key: edpkvTUqzRYhotk2YFnemLfBk8apvcSVNwTSxB6F6CaXUA64CRXgHN
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  functori:
    # tz1funU3PjPsuXvmtXMgnAckY1s4pNT6V7WJ
    key: edpkv2fhuhS4947m64XexZw2vMvr7C4zYTBFweXuWVCLbmaSqpFaT3
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  pierre_chambart:
    # tz1QvBzVmzN7F37ay4ZX12Tm2VEUmEbXJus7
    key: edpkvGiC27B2WJRC6AoFS8wwSC4rrhnTULWxq53PkoJjJSRSCvFwJn
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  mystery_baker_6:
    # tz1dqPQn5HXNJ7yjcqBx2w6sozjPXTV1kpfh
    key: edpkupKuAv85MDjsfAEFeNMS4jHwkS1dT1dRajVwoYeSs6jEbwcTPm
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "667000000000"
  oxheadfree:
    # an account with a lot of money in it
    # tz1foxFdz2ieSj8P9YxKYBTEqYbgFXXEeiQY
    key: edpkubSgCoMjB2a6vPWRNRHfGa6HUFfFyEUKoEQhWC8osnav8QzBdJ
    bootstrap_balance: "500000000000000"
    is_bootstrap_baker_account: false
    type: public
  tz1THUNA:
    # tz1THUNARo58aD5YdNGYPnWNnvd8yHPrMdsF
    # Romain's faucet
    key: edpkuh3WSwziyd6nXqDXeh48vZHp5ETxFd43EdkbzhmW98BvuLXK81
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "500000000000000"
  bakingbadfaucet:
    # baking bad maintains a telegram faucet bot
    # tz1KhnTgwoRRALBX6vRHRnydDGSBFsWtcJxc
    key: edpkuFRauFAdhipQu9s4xmfNJWmtLxPKpoaoG41gYGq5AgUA43Vxqx
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "500000000000000"
  julien:
    # julien.tesson@tezcore.com
    # for stress testing
    # tz1PicoD6HTZFNkRpN84VFUvdpT7D6xoR2QD
    key: edpktnArvYkSArFUGiBN4cmDmor9qwyTFCbAKEMbeSdT3z563SdTXm
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "50000000000000"
  tf:
    # tz3Q67aMz7gSMiQRcW729sXSfuMtkyAHYfqc
    key: p2pk66gP3wq6k9QgNwAgaGLeXc3YFfrxgYdC7cdYuJWAHYBw4hExVHW
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "667000000000"

  nomadic00:
    bootstrap_balance: '2000000000000'
    is_bootstrap_baker_account: true
    key: edpku3HFqm2abDUPG16fKXZHCCDCNLpBRvqbgQC1Ka4kFQHYi6S7Pf
    type: public
  nomadic01:
    bootstrap_balance: '2000000000000'
    is_bootstrap_baker_account: true
    key: edpkuQLedLGSNjfVXoT1PkJcERiQutZdMKWSzKHCSnEhpYjUXeE8LT
    type: public
  nomadic02:
    bootstrap_balance: '2000000000000'
    is_bootstrap_baker_account: true
    key: edpku5JHHNN4CV9XVZ2na4zwSjRaRABHBUsc9ujTGDfe98VDmrbt6N
    type: public
  nomadic03:
    bootstrap_balance: '2000000000000'
    is_bootstrap_baker_account: true
    key: edpkuf7dqkv617ZsQhavosmT5qXQxvQa3Ud2ZBQi6cKx5QEjkXm9TG
    type: public
  nomadic04:
    bootstrap_balance: '2000000000000'
    is_bootstrap_baker_account: true
    key: edpkto7unE5dMgguDMkVbAp6u6PRnEjzCCdULspJjdqJRzLHZUXN54
    type: public
  nomadic05:
    bootstrap_balance: '2000000000000'
    is_bootstrap_baker_account: true
    key: edpkum5U9Dcu8HswLaG4wDeih7HD3PJefRGLoMZSuStksbmYJeVaSe
    type: public
  nomadic06:
    bootstrap_balance: '2000000000000'
    is_bootstrap_baker_account: true
    key: edpkuyZsQw1ioHijuNSfPTJmou2HN672R3haywPotaP3LVRodbnkbD
    type: public
  nomadic07:
    bootstrap_balance: '2000000000000'
    is_bootstrap_baker_account: true
    key: edpkuGwsxhqqKN8xTTg66mFTgUuA3jU7AMH9ZwDETBg33QqKc7Xr1z
    type: public
  nomadic08:
    bootstrap_balance: '2000000000000'
    is_bootstrap_baker_account: true
    key: edpkupMPSkJKpSQxSpBD1jHdc53F1y79Ranvr1Twg7CY2i9RDqkQ3H
    type: public
  nomadic09:
    bootstrap_balance: '2000000000000'
    is_bootstrap_baker_account: true
    key: edpkukX7M9muTnqgxY3aBGkVXEXuhnxobVZKhT5zxbisbU49eD1crA
    type: public
  nomadic10:
    bootstrap_balance: '2000000000000'
    is_bootstrap_baker_account: true
    key: edpkteJqof5RFHc8JeTwTL6J9ZgMNxJT8MspjLUL7AuCAnytDxcjs5
    type: public
  nomadic11:
    bootstrap_balance: '2000000000000'
    is_bootstrap_baker_account: true
    key: edpkuEyuPpyUszCPTJeUmAVmpCaFyXah9Q1jschvyX9Z6haL5YBJ4Z
    type: public
  nomadic12:
    bootstrap_balance: '2000000000000'
    is_bootstrap_baker_account: true
    key: edpkuJUgU6iSL7xwiuFWkX8HRwTScHJTsGzPLH7g7bv9Y9WnepXBbA
    type: public
  nomadic13:
    bootstrap_balance: '2000000000000'
    is_bootstrap_baker_account: true
    key: edpktn5KiKPSrUnDkfP515rvL9okpxvzcpjev2xcCSCWJLHNkRA7Md
    type: public
  nomadic14:
    bootstrap_balance: '2000000000000'
    is_bootstrap_baker_account: true
    key: edpkvZVz1aWhgdB4QUTzwBcAhhBiiEVfHR3sWvXWJ9tUzyzopnbKdM
    type: public
  nomadic15:
    bootstrap_balance: '2000000000000'
    is_bootstrap_baker_account: true
    key: edpkvFwYwnkVMQcPC36usdkd7Vp8PMSam2asxtLg6iepvaXxerRKZE
    type: public
  nomadic16:
    bootstrap_balance: '2000000000000'
    is_bootstrap_baker_account: true
    key: edpkv9HowGporsaQNauuv8gJX1FqPTn36A4AAjfeA1bGEncZe5wg3D
    type: public
  nomadic17:
    bootstrap_balance: '2000000000000'
    is_bootstrap_baker_account: true
    key: edpkuH8anpAFPNa1NPsWeymqLgyWJ1bDSWSqnyP2dod6rqf8Mi6yw6
    type: public
  nomadic18:
    bootstrap_balance: '2000000000000'
    is_bootstrap_baker_account: true
    key: edpkvAKQvhm6PPaPh4AQp4SjxFEkjyGohoz9DMsCNUXC6GdHzzAo54
    type: public
  nomadic19:
    bootstrap_balance: '2000000000000'
    is_bootstrap_baker_account: true
    key: edpkvUf8SABxhiUXz9dhKvPqEWhanzYHpfzaKp4oBzR1ft8C8NtRCo
    type: public
