accounts:
  oxheadbaker:
    bootstrap_balance: "7500000000000"
    is_bootstrap_baker_account: true
    type: secret
    # key injected by pulumi
  tf1:
    key: edpktnhkGfR4GWZ2BWthxB796zDQtcRDaiTDbUGMwXA9stoLqzPncb
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "100000000000"
  tf2:
    key: edpkvJ4yYhB4VUv2QS3pW7dRVxs4n2gVRJakD5k3TDHPkuWMPxLU5t
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "100000000000"
  tf3:
    key: edpktfnVodSwFtQdnRLYvWQmEmihP6NBndknAY7Ld2hnpFBXiLVL6v
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "100000000000"
  tf4:
    key: edpkv5DKpGgMCLmxkCh2q4chNwZDsKykQe1A5MqQHvMSaka584C38x
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "100000000000"
  tf5:
    key: edpkur3eJCphrFcopko2onAMu4PBv7q68TL7yWxN3mB3teLhgogioq
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "100000000000"
  oxheadfree:
    # an account with a lot of money in it
    # tz1foxFdz2ieSj8P9YxKYBTEqYbgFXXEeiQY
    key: edpkubSgCoMjB2a6vPWRNRHfGa6HUFfFyEUKoEQhWC8osnav8QzBdJ
    bootstrap_balance: "5000000000000000"
    is_bootstrap_baker_account: false
    type: public
  faucet:
    # tz1foXHgRzdYdaLgX6XhpZGxbBv42LZ6ubvE
    key: edpkvGYHoY5kwq13Ak6r4fLa1GGSHKJZVe7xJFV6ZgHwdZeaHy3WZj
    bootstrap_balance: "2000000000000"
    is_bootstrap_baker_account: false
  scoru_rollup_operator:
    key: edpktnY9kXbEW1HjqDbQ4AG3hYkNunxHiRsZe72gEaHxddxNBtjG7B
    bootstrap_balance: "1000000000000"
    is_bootstrap_baker_account: false
  scoru_enduser:
    key: edpkuet91oSH1Q9i4nGJRDjdsF9W7XcAteqLQe1VqSjtMHRtDpCVFp
    bootstrap_balance: "1000000000000"
    is_bootstrap_baker_account: false
  stresstest_1:
    # a stress test account with a lot of money in it
    # tz1ST1WZv4G3pmYqZ4iYu9PtbN9M7ByxiULn
    key: edpkuLyT6wFmSdqsxA3YaukS8SX4LxpTxTLUF3oJ6vgkZfLhp5iz1U
    bootstrap_balance: "10000000000000"
    is_bootstrap_baker_account: false
  stresstest_2:
    # a stress test account with a lot of money in it
    # tz1ST2bdAVcBuRszxBrCnmL9TLzKsahgPDaZ
    key: edpktompQYh2b8ybPGHSHbdXXnPyp3qH6VKCkYvqBn8qDTheN1aH2M
    bootstrap_balance: "10000000000000"
    is_bootstrap_baker_account: false
  stresstest_3:
    # a stress test account with a lot of money in it
    # tz1ST3nnn3NhXs57Np8YFodu1C2gsXQ36Qzc
    key: edpktwUktVnwNywwK5yvC87sEntiAiNqp7kSPU3EE5Twp4LjUUXHqy
    bootstrap_balance: "10000000000000"
    is_bootstrap_baker_account: false
  stresstest_4:
    # a stress test account with a lot of money in it
    # tz1ST4LbETqS4FhD3viKk23J4MucPg8UsCaE
    key: edpkv5uv25CFXP9cs9mHeH2FaLZ6e1dmJC2eqZoaNe8GoQjtzA8S8y
    bootstrap_balance: "10000000000000"
    is_bootstrap_baker_account: false
  stresstest_5:
    # a stress test account with a lot of money in it
    # tz1ST5nQZus5LUdgvfJdcBEqDYPLBkWiKAeV
    key: edpktmmQ27SPGm4AqQZ2SPCnmAi9sQAx4g53qWDzjCtrc1mK1z4U8Y
    bootstrap_balance: "10000000000000"
    is_bootstrap_baker_account: false
  stresstest_6:
    # a stress test account with a lot of money in it
    # tz1ST6oEJv3qxdMBiqz465nWqu8DAFnSddwA
    key: edpkteQVRQRD8GoCnf4tX4BXFEVMSskBATbWS74rgWHfCKZno5dakC
    bootstrap_balance: "10000000000000"
    is_bootstrap_baker_account: false
  stresstest_7:
    # a stress test account with a lot of money in it
    # tz1ST77umYobjqYGjp6AQAYUYiEgRgB8zoJm
    key: edpkvUfRKmagvZAtUtQZaZetLyjgdtVkEwv9kUVgrW9LoQNkNGpWmh
    bootstrap_balance: "10000000000000"
    is_bootstrap_baker_account: false
  stresstest_8:
    # a stress test account with a lot of money in it
    # tz1ST8funahiy1ZuWw9Fdac7e7F9SoPDkqt5
    key: edpkujgNgCwU8xvoyjhfS5jYJuUQZ7FBjUt5dsPWZb8ZVNprKJHVqP
    bootstrap_balance: "10000000000000"
    is_bootstrap_baker_account: false
  stresstest_9:
    # a stress test account with a lot of money in it
    # tz1ST91snXGofwV4DBtX87ds7TVRTMoCYhsc
    key: edpkupAr2bNdQXDz7vquh3xKDQBeFZKg8BQiwk3dswTnHz2QDCUBYz
    bootstrap_balance: "10000000000000"
    is_bootstrap_baker_account: false

signers:
  tezos-signer-0:
    sign_for_accounts:
    - oxheadbaker

node_config_network:
  activation_account_name: oxheadbaker
  genesis:
    block: BMFCHw1mv3A71KpTuGD3MoFnkHk9wvTYjUzuR9QqiUumKGFG6pM
    protocol: Ps9mPmXaRzmzk35gbAYNCAw6UXdE2qoABTHbN2oEEc1qM7CwT9P

protocols:
  - command: alpha

activation:
  protocol_hash: ProtoALphaALphaALphaALphaALphaALphaALphaALphaDdp3zK
  protocol_parameters:
    preserved_cycles: 3
    blocks_per_cycle: 128
    blocks_per_commitment: 16
    blocks_per_stake_snapshot: 64
    cycles_per_voting_period: 1
    hard_gas_limit_per_operation: '1040000'
    hard_gas_limit_per_block: '5200000'
    proof_of_work_threshold: '-1'
    minimal_stake: '6000000000'
    seed_nonce_revelation_tip: '125000'
    baking_reward_fixed_portion: '10000000'
    baking_reward_bonus_per_slot: '4286'
    endorsing_reward_per_slot: '2857'
    hard_storage_limit_per_operation: '60000'
    origination_size: 257
    cost_per_byte: '250'
    quorum_max: 7000
    quorum_min: 2000
    min_proposal_quorum: 500
    liquidity_baking_subsidy: '2500000'
    liquidity_baking_sunset_level: 525600
    liquidity_baking_toggle_ema_threshold: 100000
    max_operations_time_to_live: 120
    minimal_block_delay: "30"
    delay_increment_per_round: "15"
    consensus_committee_size: 7000
    consensus_threshold: 4667
    minimal_participation_ratio:
      numerator: 2
      denominator: 3
    max_slashing_period: 2
    frozen_deposits_percentage: 10
    double_baking_punishment: "640000000"
    ratio_of_frozen_deposits_slashed_per_double_endorsement:
      numerator: 1
      denominator: 2
    cache_script_size: 100000000
    cache_stake_distribution_cycles: 8
    cache_sampler_state_cycles: 8
    nonce_revelation_threshold: 32
    vdf_difficulty: '10000000'
    tx_rollup_enable: true
    tx_rollup_origination_size: 4000
    tx_rollup_hard_size_limit_per_inbox: 500000
    tx_rollup_hard_size_limit_per_message: 5000
    tx_rollup_commitment_bond: "10000000000"
    tx_rollup_finality_period: 10
    tx_rollup_max_inboxes_count: 15
    tx_rollup_withdraw_period: 10
    tx_rollup_max_messages_per_inbox: 1010
    tx_rollup_max_commitments_count: 30
    tx_rollup_cost_per_byte_ema_factor: 120
    tx_rollup_max_withdrawals_per_batch: 15
    tx_rollup_max_ticket_payload_size: 2048
    tx_rollup_rejection_max_proof_size: 30000
    tx_rollup_sunset_level: 10000000
    dal_parametric:
      feature_enable: true
      number_of_slots: 256
      number_of_shards: 2048
      endorsement_lag: 2
      availability_threshold: 50
      slot_size: 1048576
      redundancy_factor: 16
      segment_size: 4096
    sc_rollup_enable: true
    sc_rollup_origination_size: 6314
    sc_rollup_challenge_window_in_blocks: 40
    sc_rollup_max_number_of_messages_per_commitment_period: 32765
    sc_rollup_stake_amount: "32000000"
    sc_rollup_commitment_period_in_blocks: 20
    sc_rollup_max_lookahead_in_blocks: 30000
    sc_rollup_max_active_outbox_levels: 20160
    sc_rollup_max_outbox_messages_per_level: 100
    sc_rollup_number_of_sections_in_dissection: 32
    sc_rollup_timeout_period_in_blocks: 500
    sc_rollup_max_number_of_cemented_commitments: 5
nodes:
  tezos-baking-node:
    instances:
      - bake_using_accounts:
          - oxheadbaker
        config:
          shell:
            history_mode: archive
          rpc:
            cors-headers: [ "content-type" ]
            cors-origin: [ "*" ]
        is_bootstrap_node: true
    runs:
      - octez_node
      - baker
      - accuser
      - vdf
    readiness_probe: false
    storage_size: 15Gi
  # Overwrite default values.yaml tezos-node
  rolling-node: null

bootstrap_peers: []
full_snapshot_url: null
rolling_snapshot_url: null
rolling_tarball_url: null
archive_tarball_url: null
images: {}
