accounts:
  oxheadbaker:
    bootstrap_balance: "7500000000000"
    is_bootstrap_baker_account: true
    type: secret
    # key injected by pulumi
  tqfree:
    bootstrap_balance: "5000000000000000"
    is_bootstrap_baker_account: false
    type: secret
    # key injected by pulumi

node_config_network:
  activation_account_name: oxheadbaker
  genesis:
    block: BMFCHw1mv3A71KpTuGD3MoFnkHk9wvTYjUzuR9QqiUumKGFG6pM
    protocol: PtYuensgYBb3G3x1hLLbCmcav8ue8Kyd2khADcL5LsT5R1hcXex

protocols:
  - command: alpha

activation:
  protocol_hash: ProtoALphaALphaALphaALphaALphaALphaALphaALphaDdp3zK
  protocol_parameters:
    preserved_cycles: 3
    blocks_per_cycle: 128
    blocks_per_commitment: 16
    blocks_per_roll_snapshot: 64
    blocks_per_voting_period: 10240
    time_between_blocks:
      - "15"
      - "7"
    endorsers_per_block: 32
    hard_gas_limit_per_operation: "1040000"
    hard_gas_limit_per_block: "5200000"
    proof_of_work_threshold: "70368744177663"
    tokens_per_roll: "8000000000"
    seed_nonce_revelation_tip: "125000"
    origination_size: 257
    block_security_deposit: "512000000"
    endorsement_security_deposit: "64000000"
     baking_reward_per_endorsement:
       - "78125"
       - "11719"
     endorsement_reward:
       - "78125"
       - "52083"
    cost_per_byte: "250"
    hard_storage_limit_per_operation: "60000"
    quorum_min: 2000
    quorum_max: 7000
    min_proposal_quorum: 500
    initial_endorsers: 24
    delay_per_missing_endorsement: "8"
    minimal_block_delay: "15"
    liquidity_baking_subsidy: "2500000"
    liquidity_baking_sunset_level: 525600
    liquidity_baking_escape_ema_threshold: 100000

nodes:
  tezos-baking-node:
    instances:
      - bake_using_accounts:
          - oxheadbaker
        config:
          shell:
            history_mode: archive
          rpc:
            cors-headers: [ "content-type" ]
            cors-origin: [ "*" ]
        is_bootstrap_node: true
    runs:
      - octez_node
      - baker
      - endorser
    storage_size: 15Gi
  # Overwrite default values.yaml tezos-node
  tezos-node: null

bootstrap_peers: []
full_snapshot_url: null
rolling_snapshot_url: null
images: {}
