images:
  tezosFaucet: ghcr.io/oxheadalpha/tezos-faucet:2.0.0
  tezosFaucetBackend: ghcr.io/oxheadalpha/tezos-faucet-backend:2.0.0

authorizedHost: # filled in by pulumi
maxBalance: 61000

config:
  application:
    name: "Tezos Nairobinet faucet"
    googleCaptchaSiteKey: #filled in by pulumi
    backendUrl: # filled in by pulumi
    githubRepo: "https://github.com/oxheadalpha/tezos-faucet"
  network:
    name: # filled in by pulumi
    rpcUrl: # filled in by pulumi
    faucetAddress: tz1a4GT7THHaGDiTxgXoatDWcZfJ5j29z5RC
    viewer: https://nairobi.tzstats.com

profiles:
  user:
    amount: 100
  baker:
    amount: 6001

disableChallenges: false

redis:
  url: "redis://redis-master:6379"

ingress:
  enabled: true
  annotations:
    "kubernetes.io/ingress.class": "nginx"
    "cert-manager.io/cluster-issuer": "letsencrypt-prod"
  host: # faucet fqdn, filled in by pulumi

