name: Pulumi Setup
on:
  workflow_call:
    inputs:
      pulumi-command:
        required: true
        type: string
    outputs:
      networks:
        description: "Pulumi networks output"
        value: ${{ jobs.pulumi.outputs.networks }}
      teztnets:
        description: "Pulumi teztnets output"
        value: ${{ jobs.pulumi.outputs.teztnets }}

jobs:
  pulumi:
    runs-on: ubuntu-latest
    outputs:
      networks: ${{ steps.pup.outputs.networks }}
      teztnets: ${{ steps.pup.outputs.teztnets }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: npm install

      - id: Auth to Gcloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: tf-teztnets
            
      - name: Install gke-gcloud-auth-plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - uses: pulumi/actions@v4
        id: pup
        with:
          command: ${{ inputs.pulumi-command }}
          stack-name: tacoinfra/teztnets/teztnets
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
